publicHoistPattern:
  - sharp
allowBuilds:
  core-js: false
  es5-ext: false
  esbuild: true
  gatsby: false
  gatsby-cli: false
  gatsby-telemetry: false
  mozjpeg: false
  pngquant-bin: false
  styled-components: false
  styled-reset: false
